[tasks.build]
description = "Build with cargo (incremental)"
run = "nix develop path:../nix#niri-switcher-dev -c cargo build --release"

[tasks.run]
description = "Build and run"
run = "./target/release/niri-switcher"
depends = ["build"]

[tasks.nix]
description = "Build with nix (clean build)"
run = "nix build path:../nix#niri-switcher"

[tasks.install]
description = "Build with nix and copy to result"
run = "nix build path:../nix#niri-switcher -o result"
