[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
trusted_config_paths = ["~/dotfiles", "~/code"]
python.uv_venv_auto = true
experimental = true
disable_tools = ["python"]

[plugins]
nix = "https://github.com/jbadeau/mise-nix.git"
